# Generated by Django 5.2.6 on 2025-09-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosAdicionales',
            fields=[
                ('id_servicios_adicionales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'servicios_adicionales',
            },
        ),
    ]
