# Generated by Django 5.2.6 on 2025-10-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_adicionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosadicionales',
            name='tipo',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
