# Generated by Django 5.2.6 on 2025-09-29 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promocion', '0001_initial'),
        ('reservas_gen', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionReserva',
            fields=[
                ('id_promo_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promocion.promocion')),
                ('reservas_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_gen.reservasgen')),
            ],
            options={
                'db_table': 'promocionreserva',
            },
        ),
    ]
