# Generated by Django 5.2.6 on 2025-09-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaHotel',
            fields=[
                ('id_tarifa_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
                ('amoblado', models.CharField(max_length=1)),
                ('baño_priv', models.CharField(max_length=1)),
                ('precio_persona', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'tarifa_hotel',
            },
        ),
    ]
