# Generated by Django 5.2.6 on 2025-09-29 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas_evento', '0001_initial'),
        ('servicios_adicionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosEvento',
            fields=[
                ('id_servicios_evento', models.AutoField(primary_key=True, serialize=False)),
                ('reservas_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_evento.reservasevento')),
                ('servicios_adicionales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_adicionales.serviciosadicionales')),
            ],
            options={
                'db_table': 'servicios_evento',
            },
        ),
    ]
