# Generated by Django 5.2.6 on 2025-09-29 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('app_paterno', models.CharField(blank=True, max_length=15, null=True)),
                ('app_materno', models.CharField(blank=True, max_length=15, null=True)),
                ('ci', models.BigIntegerField(unique=True)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=1)),
                ('rol', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
