# Generated by Django 5.2.6 on 2025-09-29 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarifa_hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('amoblado', models.CharField(max_length=1)),
                ('baño_priv', models.CharField(max_length=1)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('tarifa_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifa_hotel.tarifahotel')),
            ],
            options={
                'db_table': 'habitacion',
            },
        ),
    ]
