# Generated by Django 5.2.6 on 2025-09-29 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservasGen',
            fields=[
                ('id_reservas_gen', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=1)),
                ('pago', models.BinaryField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
            options={
                'db_table': 'reservas_gen',
            },
        ),
    ]
