# Generated by Django 5.2.6 on 2025-09-29 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_cliente', '0001_initial'),
        ('habitacion', '__first__'),
        ('reservas_gen', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('id_reserva_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('cant_personas', models.PositiveSmallIntegerField()),
                ('amoblado', models.CharField(max_length=1)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('baño_priv', models.CharField(max_length=1)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('datos_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_cliente.datoscliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
                ('reservas_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_gen.reservasgen')),
            ],
            options={
                'db_table': 'reserva_hotel',
            },
        ),
    ]
