# Generated by Django 5.2.6 on 2025-09-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCliente',
            fields=[
                ('id_datos_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('app_paterno', models.CharField(blank=True, max_length=15, null=True)),
                ('app_materno', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.IntegerField()),
                ('ci', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'datos_cliente',
            },
        ),
    ]
