# Generated by Django 5.2.6 on 2025-09-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'promocion',
            },
        ),
    ]
