# Generated by Django 5.2.6 on 2025-09-29 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_cliente', '0001_initial'),
        ('reservas_gen', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservasEvento',
            fields=[
                ('id_reservas_evento', models.AutoField(primary_key=True, serialize=False)),
                ('cant_personas', models.SmallIntegerField()),
                ('hora_ini', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('datos_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_cliente.datoscliente')),
                ('reservas_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_gen.reservasgen')),
            ],
            options={
                'db_table': 'reservas_evento',
            },
        ),
    ]
