"""
Django settings for LesEtoiles project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
import pymysql
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import default_headers


pymysql.install_as_MySQLdb()
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8o92-_i0r$99-vvbrc-!(1u1lc4rl!#3k2+$zm2a&fdsx)_6jn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['.vercel.app', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    # apps de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # tus apps
    'apps.usuario',
    'apps.administrador',
    'apps.datos_cliente',
    'apps.empleado',
    'apps.promocion',
    'apps.promocionreserva',
    'apps.reserva_hotel',
    'apps.reservas_evento',
    'apps.reservas_gen',
    'apps.servicios_adicionales',
    'apps.servicios_evento',
    'apps.tarifa_hotel',
    'apps.habitacion',

    #LIBRERIAS INSTALADAS
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
]


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LesEtoiles.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LesEtoiles.wsgi.app'
from pathlib import Path
import os


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DATABASE", "b1v3w4dxnjqmxkxgd3wk"),
        'USER': os.getenv("USER", "uuhagdv5kp1xfkn8"),
        'PASSWORD': os.getenv("PASSWORD", "TixfB0Fy2hYO69bUUbOU"),
        'HOST': os.getenv("HOST", "b1v3w4dxnjqmxkxgd3wk-mysql.services.clever-cloud.com"),
        'PORT': os.getenv("PORT", "3306"),
        
        # ⭐ AGREGAR ESTAS OPCIONES CRÍTICAS:
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            'connect_timeout': 10,  # Timeout de conexión
        },
        'CONN_MAX_AGE': 0,  # ⚠️ CRÍTICO: Desactiva conexiones persistentes para threading
        'ATOMIC_REQUESTS': False,  # No usar transacciones automáticas
    }
}

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'X-Requested-With',
    'Content-Type',
    'Authorization',
]


# CONFIGURACION JWT
SIMPLE_JWT = {
      'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
}

SIMPLE_JWT = {
    # Duración del token de acceso (ej: 60 minutos)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),

    # Duración del token de refresco (ej: 7 días)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # --- Otras configuraciones opcionales ---

    # Si quieres que los tokens de refresco roten (se emita uno nuevo cada vez que se usa)
    'ROTATE_REFRESH_TOKENS': False, # Cambia a True si lo deseas

    # Si quieres que el token de refresco antiguo se añada a la lista negra después de la rotación
    # Requiere que 'rest_framework_simplejwt.token_blacklist' esté en INSTALLED_APPS
    'BLACKLIST_AFTER_ROTATION': True,

    # Algoritmo de firma
    'ALGORITHM': 'HS256',

    # Clave secreta (por defecto usa settings.SECRET_KEY)
    # 'SIGNING_KEY': settings.SECRET_KEY,

    # Clave en el payload que identifica al usuario (por defecto 'user_id')
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Agregar esto también:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Configuración adicional importante
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',  # ⚠️ IMPORTANTE para JWT
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]