# Generated by Django 5.2.6 on 2025-12-08 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('REGISTRO', 'Registro'), ('ACTUALIZACIÓN', 'Actualización'), ('DESACTIVACIÓN', 'Desactivación'), ('INICIO DE SESIÓN', 'Inicio de sesión')], max_length=20)),
                ('tabla', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-fecha'],
            },
        ),
    ]
